apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: todo-api-config-provider
spec:
  endpoint: {{.Env.AZURE_APP_CONFIGURATION_ENDPOINT}}
  target:
    configMapName: todo-api-config
  auth:
    managedIdentityClientId: {{.Env.AZURE_AKS_IDENTITY_CLIENT_ID}}
  configuration:
    selectors:
      - keyFilter: "*"
        labelFilter: todo-api
    refresh:
      enabled: true
      monitoring:
        keyValues:
        - key: APPLICATIONINSIGHTS_CONNECTION_STRING
          label: todo-api
  secret:
    target:
      secretName: todo-api-secret
    auth:
      managedIdentityClientId: {{.Env.AZURE_AKS_IDENTITY_CLIENT_ID}}
    refresh:
      enabled: true
      interval: 10m